# Generated by Django 5.2.7 on 2025-10-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="家具名")),
                ("type", models.CharField(max_length=50, verbose_name="種類")),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                (
                    "purchase_date",
                    models.DateField(blank=True, null=True, verbose_name="購入日"),
                ),
            ],
            options={
                "verbose_name_plural": "家具アイテム",
            },
        ),
    ]
