# Generated by Django 5.2.7 on 2025-10-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furniture", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="furniture_images/",
                verbose_name="画像",
            ),
        ),
    ]
