# Generated by Django 5.2.7 on 2025-10-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furniture", "0002_item_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="タイトル"
                    ),
                ),
                (
                    "room_photo",
                    models.ImageField(
                        upload_to="room_photos/", verbose_name="部屋の画像"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                (
                    "is_featured",
                    models.BooleanField(
                        default=True, verbose_name="カルーセルに表示する"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "部屋のコーディネート画像",
            },
        ),
    ]
