# Generated by Django 5.2.7 on 2025-10-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furniture", "0003_roomimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="furniture_images/",
                verbose_name="家具画像",
            ),
        ),
    ]
