# Generated by Django 5.2.7 on 2025-10-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furniture", "0004_alter_item_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_discontinued",
            field=models.BooleanField(default=False, verbose_name="製造中止"),
        ),
        migrations.AddField(
            model_name="item",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (1, "★☆☆☆☆☆☆☆☆☆ (1/10)"),
                    (2, "★★☆☆☆☆☆☆☆☆ (2/10)"),
                    (3, "★★★☆☆☆☆☆☆☆ (3/10)"),
                    (4, "★★★★☆☆☆☆☆☆ (4/10)"),
                    (5, "★★★★★☆☆☆☆☆ (5/10)"),
                    (6, "★★★★★★☆☆☆☆ (6/10)"),
                    (7, "★★★★★★★☆☆☆ (7/10)"),
                    (8, "★★★★★★★★☆☆ (8/10)"),
                    (9, "★★★★★★★★★☆ (9/10)"),
                    (10, "★★★★★★★★★★ (10/10)"),
                ],
                default=5,
                verbose_name="満足度評価 (10段階)",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="shop_url",
            field=models.URLField(
                blank=True,
                help_text="販売元のオンラインストアなどのURLを貼り付けてください。",
                verbose_name="販売元URL",
            ),
        ),
    ]
