# Generated by Django 5.2.7 on 2025-10-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furniture", "0005_item_is_discontinued_item_rating_item_shop_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="purchase_date",
        ),
        migrations.AddField(
            model_name="item",
            name="review",
            field=models.TextField(
                blank=True,
                help_text="家具を実際に使用した感想やレビューを記載します。",
                verbose_name="使ってみた感想",
            ),
        ),
    ]
