"""
Django settings for my_furniture_site project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

# ⬇️ 【修正・追加】環境変数、パス、DB処理に必要なライブラリをインポート
import os 
import dj_database_url
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
# ⬇️ デプロイ時は環境変数で渡すため、ここでは仮のキーを残す
SECRET_KEY = os.environ.get('SECRET_KEY', "django-insecure-(p7)syj&1xx8yhyzepc!jancrvsq*g38lmesz2!6wxev*@7@fh")

# SECURITY WARNING: don't run with debug turned on in production!
# ⬇️ 【修正】環境変数 DJANGO_DEBUG に応じてDEBUGモードを切り替え
DEBUG = os.environ.get('DJANGO_DEBUG', '') != 'False' 

# ⬇️ 【修正】Renderホスト名とローカルホストを許可
ALLOWED_HOSTS = ['.render.com', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "furniture",
]

# ⬇️ 【修正】WhiteNoiseミドルウェアをMIDDLEWAREの先頭に追加
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # WhiteNoiseを追加
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "my_furniture_site.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "my_furniture_site.wsgi.application"


# Database
# ⬇️ 【修正】環境変数 (DATABASE_URL) からPostgreSQL接続情報を読み込み
DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///' + os.path.join(BASE_DIR, 'db.sqlite3'),
        conn_max_age=600 # 接続維持時間を設定
    )
}


# Password validation
# ... (AUTH_PASSWORD_VALIDATORS は省略なしで維持) ...
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# ... (LANGUAGE_CODE, TIME_ZONE, USE_I18N, USE_TZ は省略なしで維持) ...
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# ----------------------------------------------------------------------
# 【静的ファイル設定】STATIC FILES (WhiteNoise対応)
# ----------------------------------------------------------------------
STATIC_URL = "static/"

# 【新規追加】全静的ファイルを収集する場所 (Renderが利用)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') 

# プロジェクトルートの 'static/' ディレクトリも参照するように設定
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]


# ----------------------------------------------------------------------
# 【メディアファイル設定】MEDIA FILES (ユーザーアップロードファイル)
# ----------------------------------------------------------------------
MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"


# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
